version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:latest

  worker:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: celery -A app worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

  worker-beat:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: celery -A app beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  db_data: