# Generated by Django 3.2.12 on 2022-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='type')),
                ('subject', models.CharField(max_length=255, verbose_name='mail title')),
                ('body', models.TextField(verbose_name='mail body')),
            ],
        ),
    ]
